YWH_USERNAME = "" # TO CHANGE
YWH_BEARER = "" # TO CHANGE
YWH_API = "https://api.yeswehack.com"

NAME_LENGTH = 40
SCOPE_COUNT_THRESHOLD_1 = 3
SCOPE_COUNT_THRESHOLD_2 = 8
REPORT_COUNT_PER_SCOPE_THREDHOLD_1 = 5
REPORT_COUNT_PER_SCOPE_THREDHOLD_2 = 15
TOTAL_REPORT_LAST24H_THRESHOLD_1 = 0
TOTAL_REPORT_LAST24H_THRESHOLD_2 = 5
TOTAL_REPORT_LAST7D_THRESHOLD_1 = 10
TOTAL_REPORT_LAST7D_THRESHOLD_2 = 25
TOTAL_REPORT_LAST1M_THRESHOLD_1 = 15
TOTAL_REPORT_LAST1M_THRESHOLD_2 = 40
HAF_THRESHOLD_1 = 3
HAF_THRESHOLD_2 = 15
CREATION_DATE_THRESHOLD_1 = 15
CREATION_DATE_THRESHOLD_2 = 180
UPDATE_DATE_THRESHOLD_1 = 15
UPDATE_DATE_THRESHOLD_2 = 90
LAST_HACKTIVITY_DATE_THRESHOLD_1 = 7
LAST_HACKTIVITY_DATE_THRESHOLD_2 = 45

YWH_PROGS_FILE = "/tmp/ywh_programs.json"
DATASOURCE_MAX_AGE = 2
DATE_FORMAT = "%Y-%m-%d"